# Generated by Django 4.0.4 on 2022-05-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_watchlist_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='platform',
        ),
    ]
